# -*- coding: utf-8 -*-
"""Data_Preparation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ILZf_aSuMf1neTZ9ViKkvis8N9lsAA1
"""

import pandas as pd
import os 
import glob
import random

## Declare path to the mosquito folder
path = 'drive/MyDrive/DatabaseBackup/anopheles/'

## Define Path to store the final csv
store_path = 'drive/MyDrive/DatabaseBackup/csv_M0/'

train_test_split = 0.8 ## This value can be changed according to requirement

## Obtain list of all image filenames inside the mosquito folder
files = glob.glob(path+"/*/*m.jpg")

## Create a set with all unique IDs of the mosquito
ID = set();
for file in files:
  name = file.split('/')[-1].split('_')[0]
  ID.add(name)

## Create a dictionary of specimen to store all relevant images pertaining to a specimen
species_dict = {}
for id in ID:
  species_dict[id] = []

## Iterate through all filenames and arrange them according to specimen number
for fname in files:
  specimen = fname.split('/')[-1].split('_')[0]
  species_dict[specimen].append(fname);


## Lists to store train and test specimen
test_data = []
train_data = []
count = 1
total = len(ID)

## Iterate through every ID and based on random split value, keep it in train set or test_set
for id in ID:
  if count%100==0:
    print(f"Specimen Number:{count}/{total}")
  count+=1
  flag = random.random()
  if flag < train_test_split:
    train_data += species_dict[id]
  else:
    test_data += species_dict[id]


## Convert lists to pandas dataframes
train_dict = {'filename':train_data}
train_df = pd.DataFrame(train_dict)
test_dict = {'filename':test_data}
test_df = pd.DataFrame(test_dict)

def find_label(row):
  label = row.split('/')[4]
  return label

## Assign label to each specimen
train_df['label']=train_df['filename'].apply(find_label)
test_df['label']=test_df['filename'].apply(find_label)

## Save CSV Files
train_df.to_csv(path+'train.csv')
test_df.to_csv(path+'test.csv')

